version: "{build}"

os: Visual Studio 2017

clone_folder: c:\projects\CppHelperLibrary

platform: x64
configuration: Release

before_build:
  - cd c:\projects\CppHelperLibrary
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - echo Running cmake...
  - cmake -G "Visual Studio 15 2017 Win64" ..

build:
  project: build\CppHelperLibrary.sln

after_build:
  - cd c:\projects\CppHelperLibrary\build\tests\Release
  - tests.exe
